namespace:
  name: atlantest

image:
  repository: anuphnu/parse-server-example
  tag: v0.0.1
  pullPolicy: IfNotPresent
  port: 1337
  health_url: /parse/health

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 20

service:
  type: LoadBalancer
  port: 80

configmap: {
  DATABASE_URI: "mongodb://mongo-mongo-db:27017/my-db",
  SERVER_URL: "http://localhost:1337/parse",
  APP_ID: "app_id_starter"
}
